---
title: "Hypertension and microbiome"
author: "Joonatan Palmu"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
output: html_document
---
	
```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE, xecho = TRUE, message = FALSE, results='asis', cache=TRUE, warning=FALSE)
knitr::opts_chunk$set(cache.path = 'cache/', output.dir="cache/",
                      file.path = 'cache/', fig.path = 'cache/')

dir.create("rds/", showWarnings = FALSE)
```

Importing libraries:

```{r libraries, cache = FALSE}
library(dplyr)
library(tibble)
library(phyloseq)
library(microbiome)
library(finriskmetagcommon)
library(knitr)
library(tidyr)
library(vegan)
library(reshape)
library(ggpmisc)
library(Maaslin)
library(parallel)
library(officer)
library(flextable)
library(rvg)
library(tableone)
library(scales)
library(gridExtra)
```

```{r Remove temporary data, include = FALSE, cache = FALSE, eval = FALSE}
unlink("rds", recursive=TRUE)
unlink("cache", recursive=TRUE)
```

```{r Initialize docx, include = FALSE, cache = FALSE}
doc <- read_docx(path = "style/articlestyle.docx") %>%
  body_remove()

dir.create("rds", showWarnings = FALSE)
dir.create("cache", showWarnings = FALSE)

text.bold <- fp_text(font.size = 12, bold = TRUE, font.family = "Arial")
text.normal <- fp_text(font.size = 12, font.family = "Arial")
```

# Function definitions

```{r Importing functions}
source("aaro/edgeR_plot_functions.R", echo = TRUE)
source("rrbiomefunctions.R", echo = TRUE)

writetable <- function(doc, tbl,  head, foot) {
    doc <- doc %>% 
        body_add_fpar(fpar(ftext("Table . ", prop = text.bold), ftext(head, prop = text.normal)), style = "Table Caption") %>%
        body_add_flextable(tbl, align = "left") %>%
        body_add_par(foot, style = "footnote text") %>%
        body_add_break(pos = "after")
}

writeggplot <- function(doc, ggplot, header, footer, width = 7, height = 7) {
    doc <- doc %>% 
        body_add_fpar(fpar(ftext("Figure . ", prop = text.bold), ftext(header, prop = text.normal)), style = "Image Caption") %>%
        body_add_gg(value = ggplot, width = width, height = height) %>%
        body_add_par(footer, style = "footnote text") %>%
        body_add_break(pos = "after") 
}

writeimage <- function(doc, filename, header, footer, width = 7, height = 7) {
    doc <- doc %>% 
        body_add_fpar(fpar(ftext("Figure . ", prop = text.bold), ftext(header, prop = text.normal)), style = "Image Caption") %>%
        body_add_img(src = filename, width = width, height = height) %>% 
        body_add_par(footer, style = "footnote text") %>%
        body_add_break(pos = "after") 
}

```

# Loading data
	
Loading descriptions for clinical data

```{r variables, warning = FALSE}
data("phfinrisk_metadatadesc", package="finriskmetagcommon")
names.dset <- filter(phfinrisk_metadatadesc,
                     Ignored.Covariate.in.Cross.Sectional.Analysis.Aaro20181115==0)
names.dset <- bind_rows(names.dset,
                        data.frame(Covariate = c("MAP", "PULSEPRESSURE", "HYPERTENSION", "SEX"),
                                   Category = rep("Physical", 4),
                                   Name =c( "Mean artrerial pressure", "Pulse pressure", "Hypertension", "Female")))
```

Loading phyloseq object

```{r data}
pseq.genus <- readRDS("data/phfinrisk_genus_all_drop50k_2018-11-16.RDs")
pseq.species <- readRDS("data/phfinrisk_species_all_drop50k_2018-12-21.RDs")
```

Updating phyloseq objects

```{r updating phyloseq objects}
phyloseq::sample_data(pseq.genus) <- phyloseq::sample_data(filter.phenotype.data(pseq.genus))
phyloseq::sample_data(pseq.species) <- phyloseq::sample_data(filter.phenotype.data(pseq.species))
```

Sample data has dimensions (`r dim(sample_data(pseq.species))`).

```{r Characteristics}
tableone.names <- list("BL_AGE" = "Age, y (SD)",
              "SEX" = "Female, N (%)",
              "BMI" = "BMI, kg/m² (SD)",
              "SYSTM" = "Systolic blood pressure, mmHg (SD)",
              "DIASM" = "Diastolic blood pressure, mmHg (SD)",
              "PULSEPRESSURE" = "Pulse pressure, mmHg (SD)",
              "MAP" = "Mean arterial pressure, mmHg (SD)",
              "HYPERTENSION" = "Hypertension, N (%)",
              "CURR_SMOKE" = "Current smoker, N (%)",
              "DIAB" = "Diabetes mellitus, N (%)",
              "Q57X" = "Exercice, N (%)",
              "ANYDRUG" = "Antihypertensive medication, N (%)",
              "BL_USE_RX_C03" = "  Diuretics, N (%)",
              "BL_USE_RX_C07" = "  Beta blockers, N (%)",
              "BL_USE_RX_C08" = "  Calcium channel blocker, N (%)",
              "BL_USE_RX_C09" = "  Agents acting on the renin-angiotensin system, N (%)")
tableone.factors <- c("SEX", "HYPERTENSION",  "ANYDRUG", "CURR_SMOKE", "DIAB", "BL_USE_RX_C03", "BL_USE_RX_C07", "BL_USE_RX_C08", "BL_USE_RX_C09")

characteristics <- function(dset, names, factors) {
    title <- "Characteristics"
    overall <- paste0("Cases, n=", dim(dset)[1])
    tableobject <- tableone::CreateTableOne(data = dset, vars = names, factorVars = factors)
    tablecsv <- print(tableobject,
                      exact = "stage",
                      quote = FALSE,
                      noSpaces = TRUE,
                      printToggle = FALSE,
                      digits = 1,
                      pDigits = 3,
                      contDigits=1)
}

data <- characteristics(meta(pseq.species), names(tableone.names), tableone.factors) %>%
    as.data.frame %>%
    tibble::rownames_to_column(var = "rowname") %>%
    dplyr::filter(row_number() > 1) %>%
    format(justify = "left", trim = TRUE) %>%
    rowwise() %>%
    mutate(id = gsub("([A-Za-z_0-9]+).*", "\\1", rowname)) %>%
    mutate(present = id %in%  names(tableone.names)) %>%
    mutate(rowname = ifelse(present == TRUE, tableone.names[[id]], rowname)) %>%
    select(rowname, Overall)

tbl1  <- flextable(data = data) %>%
    flextable::width(j = 1, width = 3) %>%
    flextable::width(j = 2, width = 1.2)

doc <- writetable(doc, tbl1, "Continuous variables are presented as mean (standard deviation). Categorical variables reported as absolute and relative frequencies. BMI indicates body mass index.", "Characteristics of the study sample.")
```
```{r alphabeta definitions}
dset.alpha <- meta.merge.alphadiversity(pseq.species)
alphaglm <- calculateglm(dset.alpha, modelstring = "%s ~ BL_AGE + SEX + BMI + CURR_SMOKE + Q57X + DIAB + BL_USE_RX_C03 + BL_USE_RX_C07 + BL_USE_RX_C08 + BL_USE_RX_C09  + diversities_shannon")
alpha.diversity <- alphaglm %>% select(response, estimate, p.value)

adonis.species  <- readRDS("rds/adonis.species.rds")
beta.diversity <- adonis.species %>%
    data.table::rbindlist(id = "model_name") %>%
    dplyr::filter(term %in% c("MAP", "SYSTM", "DIASM", "PULSEPRESSURE", "HYPERTENSION")) %>%
    dplyr::select(response, R2)

diversity <- merge(alpha.diversity, beta.diversity, by = "response") %>%
    merge(names.dset %>% select(Covariate, Category, Name), by.x ="response", by.y = "Covariate") %>%
    mutate(Qstar = ifelse(p.value < 0.05, '*', ' '))

fig.height <- 4.0 + nrow(diversity) * 0.33
fig.permar2.text <- "R2 of variable \nin Bray-Curtis distance" # TODO latexify expression?
fig.textsize <- 15
amaxb <- diversity %>% pull(estimate) %>% abs %>% max %>% signif(., digits = 2)
```

```{r alphabeta alpha}
plot.alpha.diversity <- ggplot(diversity, aes(x=reorder(Name, R2),  y = 1, fill = estimate)) +
    geom_bar(stat="identity", color="black") +
    coord_flip() +
    scale_fill_gradientn(colours = c("darkblue", "blue", "white", "red", "darkred"),
                         values = rescale(c(-amaxb,-0.1, 0, 0.1, amaxb)),
                         name = 'Regression coefficient \nin linear model \nfor Shannon index',
                         limits = c(-1.05*amaxb, 1.05*amaxb),
                         na.value = "black") +
    theme_classic(20) +
    geom_point(aes(Name, y=0.5, shape=Qstar), show.legend=TRUE, color='black', size=20) +
    scale_shape_manual(name="",
                       values=c('*'='*', ' '=' '),
                       labels=c("*"="significant at FDR 0.05", ' '=' '),
                       breaks=c("*", ' ')) +
    xlab("") +
    ylab("") +
    theme(legend.position="right",
          legend.title=element_text(size = 20),
          legend.direction="vertical",
          legend.text=element_text(size = floor(0.75*20)),
          legend.box.margin=margin(0,0,0,0,"pt"),
          legend.margin=margin(0,0,0,0,"pt"),
          legend.justification="left",
          axis.line.y = element_line(linetype="blank"),
          axis.line.x = element_line(linetype="blank"),
          legend.title.align = 0,
          legend.text.align = 0,
          axis.text.y = element_text(color="black"),
          axis.text.x = element_text(color="black"))+
    scale_y_continuous(breaks=c(0.5), labels=c(expression(alpha)))

plot.alpha.diversity.gtable <- ggplot_gtable(ggplot_build(plot.alpha.diversity))
plot.alpha.diversity.legend <- legend_extractor(plot.alpha.diversity.gtable)
plot.alpha.diversity.yaxis <- plot.alpha.diversity.gtable$grobs[[3]]

plot.alpha.diversity <- plot.alpha.diversity +
    theme(legend.position = "none",
          axis.text.x = element_blank(),
          axis.text.y=element_blank())

plot.gtable.alpha.diversity.stripped <- ggplot_gtable(ggplot_build(plot.alpha.diversity))
```


```{r alphabeta beta}
plot.beta.diversity <- ggplot(diversity, aes(x = reorder(Name, R2), y= R2)) +
    geom_bar(stat="identity", color='black') +
    coord_flip() +
    theme_classic(fig.textsize) +
    ylab(fig.permar2.text) +
    theme(axis.text.y = element_text(color="black"),
          axis.text.x = element_text(color="black"),
          legend.position="right",
          legend.direction="vertical",
          legend.box.margin=margin(0,0,0,0,"pt"),
          legend.margin=margin(0,0,0,0,"pt"),
          legend.justification="left",
          legend.title.align = 0,
          legend.text.align = 0)

plot.gtable.beta.diversity <- ggplot_gtable(ggplot_build(plot.beta.diversity))
plot.xlab.beta.diversity <- xlabb_extractor(gtable.beta.diversity)

plot.beta.diversity <- plot.beta.diversity  +
    theme(axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          axis.title.x  =  element_blank(),
          axis.title.y = element_blank(),
          legend.position = "none")
plot.gtable.beta.diversity.stripped <- ggplot_gtable(ggplot_build(plot.beta.diversity))
```


```{r save grob}
gs4 <- list(plot.alpha.diversity.yaxis,
            plot.gtable.alpha.diversity.stripped$grobs[[6]],
            plot.gtable.beta.diversity.stripped$grobs[[6]],
            plot.alpha.diversity.legend,
            plot.alpha.diversity.gtable$grobs[[7]],
            plot.gtable.beta.diversity$grobs[[7]],
           plot.xlab.beta.diversity)
#           plot.gtable.beta.diversity.stripped[[3]])

g4 <- arrangeGrob(grobs = gs4,
            layout_matrix = rbind(
                c(1,2,8,3,NA),
                c(1,2,8,3,4),
                c(1,2,8,3,NA),
                c(1,2,8,3,NA),
                c(NA,5,NA,6,NA),
                c(NA,NA,NA,7,NA)),
            widths=c(4,0.7,0.5,5,5),
            heights=c(3,12,8,21,1,2))

ggsave(file = "cache/alpha-beta.png", plot=g4, height=fig.height, width=11)
writeimage(doc, "cache/alpha-beta.png", "Alpha-beta", "footer", width = 11, height = fig.height)
```

```{r pca}
pca.prcomp <- readRDS("rds/pca.prcomp.rds")
pca.eigs <- pca.prcomp$sdev^2
pca.percentage <- 100 * pca.eigs /sum(pca.eigs)
pca.labels <- sprintf("%s (%.2f %%)", colnames(pca.prcomp$x), pca.percentage)

pcaplot <- ggplot(cbind(meta(pseq.species), pca.prcomp$x[,1:2]), aes(x=PC1, y=PC2)) +
    geom_point(aes(color = HYPERTENSION), size = 0.5) +
    scale_color_manual(values=c("red", "blue"),
                       name= "Hypertension",
                       breaks=c("1", "0"),
                       labels=c("Yes", "No")) +
    xlab(pca.labels[1]) +
    ylab(pca.labels[2]) +
    coord_fixed() +
    scale_x_continuous(breaks=seq(-100, 100, 20)) +
    scale_y_continuous(breaks=seq(-30, 30, 10)) +
    theme_classic() +
    theme(text = element_text(size=20),
          legend.justification=c(1,0),
          legend.position=c(1.03, 0.75),
          legend.title=element_text(size = 20),
          legend.direction="vertical",
          legend.text=element_text(size = floor(0.75*20)),
          legend.box.margin = margin(1, 1, 1, 1, "mm"),
          legend.box.background = element_rect(colour = "black"))

ggsave(file = "cache/pca.png", plot = pcaplot, height = 5, width = 9, dpi = 300)

writeimage(doc, "cache/pca.png", "Alpha-beta", "footer", width = 11, height = fig.height)
```

```{r maaslin}
maas.results.df.signf <- read.table("maaslin_core/maaslin_core_merged_phfinrisk_genus.txt", header=TRUE, sep='\t') %>%
    merge(names.dset %>% select(Covariate, Category, Name), by.x ="Variable", by.y = "Covariate") %>%
    dplyr::mutate(Qval = p.adjust(P.value, method="BH"),
           beta = Coefficient) %>%
   dplyr::filter(Qval < 0.05) 

maaslinplot <- plot_maaslin_heatmap_final(maas.results.df.signf %>% dplyr::filter(Variable != "HYPERTENSION"),
                      xlab.text="Genera",
                      beta.maxabs=max(abs(maas.results.df.signf[,'beta'])),
                      order.by.category=FALSE)

writeggplot(doc, maaslinplot, "maaslin", "footer", width = 7, height = 3)
```

```{r}
``

```{r Write docx to file, cache = FALSE, results = FALSE, include = FALSE}
print(doc, target = "articletwo.docx")
```
