---
title: "Compare pseqs"
author: "Joonatan Palmu"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
output: html_document
---
	
```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE, xecho = TRUE, message = FALSE, results='asis', cache=FALSE, warning=FALSE)
knitr::opts_chunk$set(cache.path = 'cache/', output.dir="cache/",
                      file.path = 'cache/', fig.path = 'cache/')

dir.create("rds-comparepseqs/", showWarnings = FALSE)
dir.create("session/", showWarnings = FALSE)
```

```{r packrat, include = FALSE, eval = FALSE}
packrat::opts$ignored.packages(c("Maaslin", "finriskmetagcommon", "biomformat",
                                 "microbiome", "phyloseq" ))
packrat::snapshot()
```

```{r Command line arguments}
now <- format(Sys.time(), '%Y%m%d-%H%M%S')

if (exists("args")) {
    if ("time" %in% names(args)) now <- args$time
    
    if("clean" %in% names(args)) {
        unlink("rds-comparepseqs", recursive=TRUE)
        unlink("cache", recursive=TRUE)
    }
    if ("loadlast" %in% names(args) )
        load("session/comparepseqs.Rdata")

    if ("subset" %in% names(args))
        subset.run <- as.numeric(args$subset)
}
```

# Importing libraries:

```{r libraries}
library(dplyr)
library(tibble)
library(phyloseq)
library(microbiome)
library(parallel)
library(knitr)
library(gridExtra)
library(vegan)
library(ggpubr)
library(broom)
library(tidyr)
library(GGally)
```

### RR biome functions

<details>
  <summary>Open/Close</summary>
  
```{r RR biome functions, code=readLines("articletwo-rrbiome.R")}
source("articletwo-rrbiome.R")
```

</details>

### Plot functions

<details>
  <summary>Open/Close</summary>

```{r Plot functions, code=readLines("articletwo-ggplot.R")}
source("articletwo-ggplot.R")
```

</details>

# Loading data

Loading descriptions for clinical data

```{r variables, warning = FALSE}
names.dset <- getdescriptions()
```


 phyloseq-objektit: 1) SHOGUN 2) CENTRIFUGE 3) NCBI70 4) GTDB 5) 16S

```{r constants}
fo.alpha.min <- "%s ~ BL_AGE + SEX  + diversities_shannon"
fo.alpha.full <- "%s ~ BL_AGE + SEX + BMI + CURR_SMOKE + Q57X + BL_USE_RX_C03 + BL_USE_RX_C07 + BL_USE_RX_C08 + BL_USE_RX_C09 + diversities_shannon" # MISSING DIAB

covariates.min <- c("BL_AGE", "SEX")
covariates.full <- c("BL_AGE", "SEX", "BMI", "CURR_SMOKE",
                         "Q57X", "BL_USE_RX_C03", "BL_USE_RX_C07",
                         "BL_USE_RX_C08", "BL_USE_RX_C09")
```

```{r rds files}
rds <- list("shogun" = "data/phfinrisk_species_all_drop50k_2018-12-21.RDs",
            "centrifuge" = "data/phfinrisk_centrifuge_species_all_2018-11-30.RDs",
            "gtdb" = "data/phfinrisk_gtdb_species_all_drop50k_2019-01-14.RDs",
            "ncbi" = "data/phfinrisk_custom70_species_all_2019-01-29.RDs",
            "R16S" = "data/phfinrisk_16S_otu_raw_2019-02-19.RDs")
```

```{r subset runs}
if (exists("subset.run")) {
    message(sprintf("Subset %s of %s", subset.run, rds[[subset.run]]))
    rds <- rds[subset.run]
}
``` 

```{r alpha scatter, include = FALSE, eval = FALSE}
rds = rds[c(1,2,4)]
ret <- list()

for (key in names(rds)) {
    missing = list()

    if (!file.exists(paste0("rds-comparepseqs/alphadistribution-", key , ".rds"))) {
        missing$alphadistribution = TRUE
    } else {
        alphadistribution <- readRDS(file =
                                         paste0("rds-comparepseqs/alphadistribution-",
                                                key , ".rds"))
    }
    
    ret[[key]] = list("alphadistribution" = alphadistribution)
}
```

```{R models}
ret <- list()

for (key in names(rds)) {
    missing = list()

    if (!file.exists(paste0("rds-comparepseqs/alphadistribution-", key , ".rds"))) {
        missing$alphadistribution = TRUE
    } else {
        alphadistribution <- readRDS(file =
                                         paste0("rds-comparepseqs/alphadistribution-",
                                                key , ".rds"))
    }

    if (!file.exists(paste0("rds-comparepseqs/alpha-", key , ".rds"))) {
        missing$alpha = TRUE
    } else {
        alphadiversity <- readRDS(file = paste0("rds-comparepseqs/alpha-", key , ".rds"))
    }

    if (!file.exists(paste0("rds-comparepseqs/bray-", key , ".rds"))) {
        missing$bray = TRUE
    } else {
        bray.dist.matrix <- readRDS(file = paste0("rds-comparepseqs/bray-", key , ".rds"))
    }
    
    if (!file.exists(paste0("rds-comparepseqs/beta-", key , ".rds"))) {
        missing$beta = TRUE
    } else {
        betadiversity <- readRDS(file = paste0("rds-comparepseqs/beta-", key , ".rds"))
    }

    if (length(missing) > 0) {
        pseq <- import_filter_data(rds[[key]],
                                   included = c("MEN", "BL_AGE", "SYSTM", "DIASM", "BMI",
                                                "CURR_SMOKE", "BL_USE_RX_C09",
                                                "Q57X", "BL_USE_RX_C03",
                                                "BL_USE_RX_C07", "BL_USE_RX_C08"))
        dset <- meta.merge.alphadiversity(pseq) %>%
            mutate(diversities_shannon = as.numeric(scale(diversities_shannon)))

        if ("alphadistribution" %in% names(missing)) {
            message("Missing alpha distribution")
            alphadistribution <- dset %>%
                mutate(!!key := diversities_shannon) %>%
                select(Sample_ID, key)
            saveRDS(alphadistribution,
                    file = paste0("rds-comparepseqs/alphadistribution-", key , ".rds"))
        }    

        if ("alpha" %in% names(missing)) {
            message("Missing alpha")
            alphadiversity <- list(min =  calculateglm(dset, modelstring = fo.alpha.min),
                                   full = calculateglm(dset, modelstring = fo.alpha.full))
            saveRDS(alphadiversity, file = paste0("rds-comparepseqs/alpha-", key , ".rds"))
        }

        if ("bray" %in% names(missing)) {
            message("Missing Bray")
            bray.dist.matrix <- calculate.beta.matrix(pseq)
            saveRDS(bray.dist.matrix, file = paste0("rds-comparepseqs/bray-", key , ".rds"))
        }
    
        if ("beta" %in% names(missing)) {
            message("Missing beta")
            betadiversity <- list(min = calculateadonis(dset = dset,
                                                        matrix = bray.dist.matrix,
                                                        covariates = covariates.min,
                                                        npermutations = 100),
                                  full = calculateadonis(dset = dset,
                                                         matrix = bray.dist.matrix,
                                                         covariates = covariates.full,
                                                         npermutations = 100))
            saveRDS(betadiversity, file = paste0("rds-comparepseqs/beta-", key , ".rds"))
        }
    }

    ret[[key]] = list("alphadiversity" = alphadiversity,
                      "betadiversity" = betadiversity,
                      "alphadistribution" = alphadistribution)
}
```

```{r plot alpha-beta}
names(rds)
if (!exists("subset.run")) {
    plotlist <- list()

    for (key in names(rds)) {
        diversities <- mergediversities(ret[[key]][["alphadiversity"]],
                                        ret[[key]][["betadiversity"]])

        alpha.diversity.min <- plot.alpha(diversities$min, alphabreaks = c(-0.15, -0.10, -0.05, -0.01, 0))
        alpha.diversity.full <- plot.alpha(diversities$full, alphabreaks = c(-0.15, -0.10, -0.05, -0.01, -0))

        beta.diversity.min <- plot.beta(diversities$min)
        beta.diversity.full <- plot.beta(diversities$full)

        gs4 <- list(alpha.diversity.min$yaxis,
                    alpha.diversity.min$plot,
                    beta.diversity.min$plot,
                    alpha.diversity.min$legend,
                    alpha.diversity.min$xaxis,
                    beta.diversity.min$xaxis,
                    beta.diversity.min$xlab,
                    text_grob(sprintf("A. %s (%s)", key, paste(covariates.min, collapse = ", ")),
                              size = 16,
                              just = "left"),
                    alpha.diversity.full$yaxis,
                    alpha.diversity.full$plot,
                    beta.diversity.full$plot,  
                    alpha.diversity.full$xaxis,
                    beta.diversity.full$xaxis,
                    beta.diversity.full$xlab,
                    text_grob(sprintf("B. %s (%s)", key, paste(covariates.full %>%
                                                               gsub("BL_USE_", "", .), collapse = ", ")),
                              size = 16, just = "left"))
        
        g4 <- arrangeGrob(grobs = gs4,
                          layout_matrix = rbind(
                              c(8,    NA,    NA, NA,   NA, NA, NA),
                              c(NA, 1,    2,    NA, 3, NA, NA),
                              c(NA, 1,    2,    NA, 3, NA, 4),
                              c(NA, NA, 5,    NA,6, NA, NA),
                              c(NA, NA, NA, NA,7, NA, NA),
                              c(15,    NA,    NA, NA,   NA, NA, NA),
                              c(NA, 9,    10,  NA,  11, NA, NA),
                              c(NA, 9,    10,  NA,  11, NA, NA),
                              c(NA, NA, 12,   NA, 13, NA, NA),
                              c(NA, NA, NA, NA,14, NA, NA)),
                          widths=c(0.7, 4, 0.7, 0.1, 5, 0.7, 3),
                          heights=rep(c(1, 1, 6, 1, 2), 2))

        ggsave(file = paste0("cache/alpha-beta-", key , ".png"), plot=g4, height=6, width=9)
        
        plotlist[[key]] = g4
    }

    g <- arrangeGrob(grobs = plotlist, ncol=2)
    ggsave(file="cache/plotlist.png", g, height=6*length(plotlist)/1.5, width=10*2)

} else {
    message("Skipping graphics")
}
```

```{r debug, eval = FALSE}
alphalist <- c()
for (key in names(rds)) {
    alphalist <- c(alphalist,
              ret[[key]]$alphadiversity$min %>% pull(estimate),
              ret[[key]]$alphadiversity$full %>% pull(estimate))
}

summary(alphalist)
```

```{r alpha size, eval = FALSE}
pseq <- import_filter_data(rds[["gtdb"]])

dset <- meta.merge.alphadiversity(pseq) %>%
    mutate(diversities_shannon = scale(diversities_shannon))

dset %>%
    select(MAP, diversities_shannon) %>%
    gather(key, value) %>%
    group_by(key) %>%
    summarise_all(funs(N = n(),
                       min = min(as.numeric(value), na.rm = TRUE),
                       max = max(as.numeric(value), na.rm = TRUE),
                       Mean = mean(as.numeric(value), na.rm = TRUE),
                       SD = sd(as.numeric(value), na.rm = TRUE),
                       NAs = sum(is.na(value))))  %>%
    kable()

lm(sprintf(fo.alpha.full, "SYSTM"), data = dset) %>% summary
```

# Alpha scatter

```{r draw alpha distribution scatter plot, eval = FALSE}
scatterplot.df <- lapply(ret, function(x) x$alphadistribution) %>%
    Reduce(function(x, y) merge(x, y, all=TRUE, by="Sample_ID"), .) %>%
    select(-Sample_ID) %>%
    na.omit()

galphascatter <- ggpairs(scatterplot.df,
                         lower = list(continuous = wrap("points",
                                                        alpha = 0.3,
                                                        size=0.1), 
                                      combo = wrap("dot",
                                                   alpha = 0.4,
                                                   size=0.2))) +
    theme(legend.position = "none", 
          panel.grid.major = element_blank(), 
          axis.ticks = element_blank(), 
          panel.border = element_rect(linetype = "dashed", colour = "black", fill = NA))


ggsave(file = paste0("cache/ggpairs-alphas.png"),
       plot= galphascatter,
       height=6,
       width=9,
       unit = "in",
       dpi = 300)


```

Full model R2

```{r diff beta debug, eval = FALSE}
betadf <- data.frame()
for (key in names(rds)) {
    moddf.full <- Reduce(function(...) merge(..., all=T), ret[[key]][["betadiversity"]]$full) %>%
        dplyr::filter(response == term) %>%
        mutate(model = key, covariates = "full") %>%
        select(term, model, covariates, R2)
    moddf.min <- Reduce(function(...) merge(..., all=T), ret[[key]][["betadiversity"]]$min) %>%
        dplyr::filter(response == term) %>%
        mutate(model = key, covariates = "min") %>%
        select(term, model, covariates, R2)
    betadf <- rbind(betadf, moddf.full, moddf.min)
}

betadf %>% arrange(term) %>% spread(model, R2) %>% kable
```

```{r debugging adonis, eval = FALSE}
pseq <- import_filter_data(rds[["gtdb"]])

dset <- meta.merge.alphadiversity(pseq) %>%
    mutate(diversities_shannon = scale(diversities_shannon))

bray.dist.matrix <- readRDS(file = paste0("rds-comparepseqs/bray-gtdb.rds"))

dset.sample <- dset %>% sample_n(50)

dset.ids <- dset.sample %>% pull(Sample_ID)

betadiversity <- list(min = calculateadonis(dset = dset.sample,
                                            matrix = bray.dist.matrix[dset.ids, dset.ids],
                                            covariates = covariates.min,
                                            npermutations = 10000),
                      full = calculateadonis(dset = dset.sample,
                                      matrix = bray.dist.matrix[dset.ids, dset.ids],
                                      covariates = covariates.full,
                                      npermutations = 2))

betadiversity$full

betadf <- data.frame()
for (key in names(rds)) {
    moddf.full <- Reduce(function(...) merge(..., all=T), betadiversity$full) %>%
        dplyr::filter(response == term) %>%
        mutate(model = key, covariates = "full") %>%
        select(term, model, covariates, R2)
    moddf.min <- Reduce(function(...) merge(..., all=T), betadiversity$min) %>%
        dplyr::filter(response == term) %>%
        mutate(model = key, covariates = "min") %>%
        select(term, model, covariates, R2)
    betadf <- rbind(betadf, moddf.full, moddf.min)
}
betadf %>% arrange(term) %>% spread(model, R2) %>% kable


```
