---
title: "Hypertension and microbiome"
author: "Joonatan Palmu"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE, echo = TRUE, message = FALSE, results='asis', cache=TRUE, warning=FALSE)
knitr::opts_chunk$set(cache.path = 'cache/', output.dir="cache/",
                      file.path = 'cache/', fig.path = 'cache/')
```

Importing libraries

```{r libraries}
library(dplyr)
library(tibble)
library(phyloseq)
library(microbiome)
library(finriskmetagcommon)
library(knitr)
library(tidyr)
library(vegan)
library(reshape)
library(ggpmisc)
library(Maaslin)
```

```{r clear session}
remove(list = ls())
```

```{R data}
pseq.genus <- readRDS("data/phfinrisk_genus_all_drop50k_2018-11-16.RDs")
pseq.species <- readRDS("data/phfinrisk_species_ok_drop50k_2018-11-16.RDs")
```

```{r}
summarize_phyloseq(pseq)
ntaxa(pseq)
pseq %>% taxa() %>% sort
phfg.pseq.rel %>% rank_names()
subset_taxa(pseq.species, Genus == "Lactobacillus")
taxa_unique(phfg.pseq.rel, "Phylum")
abundances(phfg.pseq.rel)

```

```{r}

taxa <- subset_taxa(pseq.species, Genus=="Lactobacillus") %>% taxa()
taxa
taxa %>% kable

```
