---
title: "Redundancy analysis for hypertension"
author: "Joonatan Palmu"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
output: html_document
---
	
```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE, xecho = TRUE, message = FALSE, results='asis', cache=FALSE, warning=FALSE)
knitr::opts_chunk$set(cache.path = 'cache/', output.dir="cache/",
                      file.path = 'cache/', fig.path = 'cache/')

dir.create("rds/", showWarnings = FALSE)
dir.create("session/", showWarnings = FALSE)
```

```{r libraries, cache = FALSE}
library(dplyr)
library(vegan)
library(broom)
library(tibble)
library(knitr)
library(phyloseq)
library(microbiome)
library(purrr)
library(parallel)
```

### RR biome functions

<details>
  <summary>Open/Close</summary>
  
```{r RR biome functions, code=readLines("articletwo-rrbiome.R")}
source("articletwo-rrbiome.R")
```

</details>


Loading phyloseq object

```{r data}
pseq.genus <- import_filter_data("data/phfinrisk_genus_all_drop50k_2018-11-16.RDs")
pseq.species <- import_filter_data("data/phfinrisk_species_all_drop50k_2018-12-21.RDs")
pseq.genus.core <- core(pseq.genus, detection = 0.001, prevalence = 0.01)
```

```{r abundances to matrix function}
transform.matrix <- function(pseq, transformation = "clr") {
    microbiome::transform(pseq, transformation) %>%
        microbiome::abundances() %>%
            t() %>%
            as.matrix()
 }
```

```{r transformations}
rda.abundances.species  <- transform.matrix(pseq.species)
rda.abundances.genus  <- transform.matrix(pseq.genus)
rda.abundances.genus.core  <- transform.matrix(pseq.genus.core)
```
## All models

```{r model function}
modelfunction <- function(x,
                          rda.abund,
                          df.meta,
                          modelstr = "rda.abund ~ %s + Condition(%s)",
                          permutations = 1000) {
    covariates <- c("BL_AGE", "SEX", "BMI", "CURR_SMOKE", "Q57X",
                   "DIAB", "BL_USE_RX_C03", "BL_USE_RX_C07",
                   "BL_USE_RX_C08", "BL_USE_RX_C09")
    fo <- sprintf(modelstr, x, paste0(covariates, collapse = "+"))
    model <- rda(as.formula(fo), data = df.meta)
    anova.term <- anova(model, by="term", perm=permutations)
    data.frame(var = as.character(x),
               beta = coef(model)[,1][[ifelse(x == "HYPERTENSION", "HYPERTENSION1", x)]],
               conditioned = ifelse("partial.chi" %in% names(summary(model)),
                                        summary(model)$partial.chi,
                                        0),
               constrained = summary(model)$constr.chi,
               unconstrained = summary(model)$unconst.chi,
                p.anova = anova.term[["Pr(>F)"]][1],
               fo = fo)
}
```

```{r return parser}
returnparser <- function(ret){
    res <- do.call(rbind, ret) %>%
        mutate(RDA.total =  conditioned + constrained + unconstrained,
               conditioned = conditioned/RDA.total,
               constrained = constrained/RDA.total,
               unconstrained = unconstrained/RDA.total
               ) 

    res %>%
        dplyr::select(var,
                      beta,
                      p.anova,
                      conditioned,
                      constrained,
                      unconstrained) %>%
        kable()
}
```

### Species

```{r models species}
ret.species <- mclapply(c2l("SYSTM", "DIASM", "PULSEPRESSURE", "MAP", "HYPERTENSION"),
              modelfunction,
              rda.abund = rda.abundances.species,
              df.meta = meta(pseq.species),
              mc.cores = 5)
returnparser(ret.species)
```

### Genus

```{r models genus}
ret.genus <- mclapply(c2l("SYSTM", "DIASM", "PULSEPRESSURE", "MAP", "HYPERTENSION"),
              modelfunction,
              rda.abund = rda.abundances.genus,
              df.meta = meta(pseq.genus),
              mc.cores = 5)
returnparser(ret.genus)
```

### Genus core

```{r models genus core}
ret.genus.core <- mclapply(c2l("SYSTM", "DIASM", "PULSEPRESSURE", "MAP", "HYPERTENSION"),
              modelfunction,
              rda.abund = rda.abundances.genus.core,
              df.meta = meta(pseq.genus.core),
              mc.cores = 5)
returnparser(ret.genus.core)
```

## Example model (species, systole)

RDA model

```{r rda}
ex.rda <- rda(rda.abundances.species ~ SYSTM + Condition(BL_AGE + SEX + BMI + CURR_SMOKE + Q57X
                                                        + DIAB + BL_USE_RX_C03 + BL_USE_RX_C07 +
                                                        + BL_USE_RX_C08 + BL_USE_RX_C09),
              data = meta(pseq.species))
```

RDA summary

```{r rda summary}
data.frame(Inertia = c(
                   Conditioned = summary(ex.rda)$partial.chi,
                   Constrained = summary(ex.rda)$constr.chi,
                   Unconstrained = summary(ex.rda)$unconst.chi)) %>%
        tibble::rownames_to_column("Variance") %>%
        mutate(Proportion = Inertia/sum(Inertia)) %>%
        mutate_at(2:2, funs(round(., 1))) %>%
        mutate_at(3:3, funs(round(., 5))) %>%
        kable
```

RDA r-squares

```{r rda rsqr}
RsquareAdj(ex.rda)$r.squared %>% kable
```

RDA coefficients

```{r rda coef}
coef(ex.rda) %>% kable
```

Anova

```{r anova}
anova.term <- anova(ex.rda, by="term", perm=1000)
anova.term %>% kable
```

Plot

```{r rda plot}
plot(ex.rda)
```

## Non-partial RDA species

```{r species non condition covariatesmodels test, eval = FALSE}
rda.subset <- rda.abundances.species[1:100, 1:100]
meta.subset <- meta(pseq.species) %>%
    tibble::rownames_to_column("id") %>%
    dplyr::filter(id %in% rownames(rda.subset)) 

ret.species <- mclapply(c2l("SYSTM", "DIASM", "PULSEPRESSURE", "MAP", "HYPERTENSION"),
              modelfunction,
              rda.abund = rda.subset,
              df.meta = meta.subset,
              modelstr = "rda.abund ~ %s + %s",
              mc.cores = 5)

returnparser(ret.species)
```

```{r save session}
save.image(file = paste0("session/rda.Rdata"))
```
